
// <copyright file="DtoGenerator.tt" company="Elvian Empire">
//  Copyright © Elvian Empire. All Rights Reserved.
// </copyright>
// Code generated by a template
using System;

namespace EveTrader.Core.Model.Trader
{
    public class AccountsDto
    {
                                        
        public System.Int64 ID { get; set; }	
    
                                                    
        public System.String ApiKey { get; set; }	
    
                                                                                    }
    
    public class ApiCacheDto
    {
                                        
        public System.Int64 ID { get; set; }	
    
                                                    
        public System.String RequestString { get; set; }	
    
                                                    
        public System.DateTime RequestDate { get; set; }	
    
                                                    
        public System.String Data { get; set; }	
    
                                                                }
    
    public class JournalDto
    {
                                        
        public System.Int64 ID { get; set; }	
    
                                                    
        public System.Int64 RefTypeID { get; set; }	
    
                                                    
        public System.String OwnerName1 { get; set; }	
    
                                                    
        public System.Int64 OwnerID1 { get; set; }	
    
                                                    
        public System.String OwnerName2 { get; set; }	
    
                                                    
        public System.Int64 OwnerID2 { get; set; }	
    
                                                    
        public System.String ArgName1 { get; set; }	
    
                                                    
        public System.Int64 ArgID1 { get; set; }	
    
                                                    
        public System.Decimal Amount { get; set; }	
    
                                                    
        public System.Decimal Balance { get; set; }	
    
                                                    
        public System.String Reason { get; set; }	
    
                                                    
        public System.Int64 TaxReceiverID { get; set; }	
    
                                                    
        public System.Decimal TaxAmount { get; set; }	
    
                                                    
        public System.DateTime Date { get; set; }	
    
                                                    
        public System.DateTime DateTime { get; set; }	
    
                                                                                                        }
    
    public class ApiJournalDto
    {
                                        
        public System.Int64 ExternalID { get; set; }	
    
                                                    
        public System.Int64 ID { get; set; }	
    
                                                    
        public System.Int64 RefTypeID { get; set; }	
    
                                                    
        public System.String OwnerName1 { get; set; }	
    
                                                    
        public System.Int64 OwnerID1 { get; set; }	
    
                                                    
        public System.String OwnerName2 { get; set; }	
    
                                                    
        public System.Int64 OwnerID2 { get; set; }	
    
                                                    
        public System.String ArgName1 { get; set; }	
    
                                                    
        public System.Int64 ArgID1 { get; set; }	
    
                                                    
        public System.Decimal Amount { get; set; }	
    
                                                    
        public System.Decimal Balance { get; set; }	
    
                                                    
        public System.String Reason { get; set; }	
    
                                                    
        public System.Int64 TaxReceiverID { get; set; }	
    
                                                    
        public System.Decimal TaxAmount { get; set; }	
    
                                                    
        public System.DateTime Date { get; set; }	
    
                                                    
        public System.DateTime DateTime { get; set; }	
    
                                                                                                        }
    
    public class TransactionsDto
    {
                                        
        public System.Int64 ID { get; set; }	
    
                                                    
        public System.Int64 Quantity { get; set; }	
    
                                                    
        public System.String TypeName { get; set; }	
    
                                                    
        public System.Int64 TypeID { get; set; }	
    
                                                    
        public System.Decimal Price { get; set; }	
    
                                                    
        public System.Int64 ClientID { get; set; }	
    
                                                    
        public System.String ClientName { get; set; }	
    
                                                    
        public System.Int64 StationID { get; set; }	
    
                                                    
        public System.String StationName { get; set; }	
    
                                                    
        public System.Int64 TransactionType { get; set; }	
    
                                                    
        public System.Int64 TransactionFor { get; set; }	
    
                                                    
        public System.DateTime Date { get; set; }	
    
                                                    
        public System.Boolean Ignored { get; set; }	
    
                                                    
        public System.DateTime DateTime { get; set; }	
    
                                                                                                        }
    
    public class ApiTransactionsDto
    {
                                        
        public System.Int64 ExternalID { get; set; }	
    
                                                    
        public System.Int64 ID { get; set; }	
    
                                                    
        public System.Int64 Quantity { get; set; }	
    
                                                    
        public System.String TypeName { get; set; }	
    
                                                    
        public System.Int64 TypeID { get; set; }	
    
                                                    
        public System.Decimal Price { get; set; }	
    
                                                    
        public System.Int64 ClientID { get; set; }	
    
                                                    
        public System.String ClientName { get; set; }	
    
                                                    
        public System.Int64 StationID { get; set; }	
    
                                                    
        public System.String StationName { get; set; }	
    
                                                    
        public System.Int64 TransactionType { get; set; }	
    
                                                    
        public System.Int64 TransactionFor { get; set; }	
    
                                                    
        public System.DateTime Date { get; set; }	
    
                                                    
        public System.Boolean Ignored { get; set; }	
    
                                                    
        public System.DateTime DateTime { get; set; }	
    
                                                                                                        }
    
    public class ApplicationLogDto
    {
                                        
        public System.Int64 ID { get; set; }	
    
                                                    
        public System.DateTime Date { get; set; }	
    
                                                    
        public System.String Message { get; set; }	
    
                                                    
        public System.String CallingClass { get; set; }	
    
                                                                }
    
    public class CachedPriceInfosDto
    {
                                        
        public System.Int64 TypeID { get; set; }	
    
                                                    
        public System.Decimal BuyPrice { get; set; }	
    
                                                    
        public System.Decimal SellPrice { get; set; }	
    
                                                                }
    
    public class EntitiesDto
    {
                                        
        public System.Int64 ID { get; set; }	
    
                                                    
        public System.String Name { get; set; }	
    
                                                                                                                                                }
    
    public class CharactersDto
    {
                                        
        public System.String Race { get; set; }	
    
                                                    
        public System.String Gender { get; set; }	
    
                                                    
        public System.String Bloodline { get; set; }	
    
                                                    
        public System.Decimal Balance { get; set; }	
    
                                                                                            
        public System.Int64 ID { get; set; }	
    
                                                    
        public System.String Name { get; set; }	
    
                                                                                                                                                }
    
    public class CorporationsDto
    {
                                        
        public System.String Ticker { get; set; }	
    
                                                    
        public System.Boolean Npc { get; set; }	
    
                                                    
        public System.Int64 ApiCharacterID { get; set; }	
    
                                                                        
        public System.Int64 ID { get; set; }	
    
                                                    
        public System.String Name { get; set; }	
    
                                                                                                                                                }
    
    public class CustomJournalDto
    {
                                        
        public System.DateTime Created { get; set; }	
    
                                                    
        public System.String Description { get; set; }	
    
                                                    
        public System.Int64 ID { get; set; }	
    
                                                    
        public System.Int64 RefTypeID { get; set; }	
    
                                                    
        public System.String OwnerName1 { get; set; }	
    
                                                    
        public System.Int64 OwnerID1 { get; set; }	
    
                                                    
        public System.String OwnerName2 { get; set; }	
    
                                                    
        public System.Int64 OwnerID2 { get; set; }	
    
                                                    
        public System.String ArgName1 { get; set; }	
    
                                                    
        public System.Int64 ArgID1 { get; set; }	
    
                                                    
        public System.Decimal Amount { get; set; }	
    
                                                    
        public System.Decimal Balance { get; set; }	
    
                                                    
        public System.String Reason { get; set; }	
    
                                                    
        public System.Int64 TaxReceiverID { get; set; }	
    
                                                    
        public System.Decimal TaxAmount { get; set; }	
    
                                                    
        public System.DateTime Date { get; set; }	
    
                                                    
        public System.DateTime DateTime { get; set; }	
    
                                                                                                        }
    
    public class CustomTransactionsDto
    {
                                        
        public System.DateTime Created { get; set; }	
    
                                                    
        public System.String Description { get; set; }	
    
                                                    
        public System.Int64 ID { get; set; }	
    
                                                    
        public System.Int64 Quantity { get; set; }	
    
                                                    
        public System.String TypeName { get; set; }	
    
                                                    
        public System.Int64 TypeID { get; set; }	
    
                                                    
        public System.Decimal Price { get; set; }	
    
                                                    
        public System.Int64 ClientID { get; set; }	
    
                                                    
        public System.String ClientName { get; set; }	
    
                                                    
        public System.Int64 StationID { get; set; }	
    
                                                    
        public System.String StationName { get; set; }	
    
                                                    
        public System.Int64 TransactionType { get; set; }	
    
                                                    
        public System.Int64 TransactionFor { get; set; }	
    
                                                    
        public System.DateTime Date { get; set; }	
    
                                                    
        public System.Boolean Ignored { get; set; }	
    
                                                    
        public System.DateTime DateTime { get; set; }	
    
                                                                                                        }
    
    public class MarketOrdersDto
    {
                                        
        public System.Int64 ID { get; set; }	
    
                                                    
        public System.Int64 StationID { get; set; }	
    
                                                    
        public System.Int64 VolumeEntered { get; set; }	
    
                                                    
        public System.Int64 VolumeRemaining { get; set; }	
    
                                                    
        public System.Int64 MinimumVolume { get; set; }	
    
                                                    
        public System.Int64 OrderState { get; set; }	
    
                                                    
        public System.Int64 TypeID { get; set; }	
    
                                                    
        public System.Int64 Range { get; set; }	
    
                                                    
        public System.Int64 AccountKey { get; set; }	
    
                                                    
        public System.Int64 Duration { get; set; }	
    
                                                    
        public System.Decimal Escrow { get; set; }	
    
                                                    
        public System.Decimal Price { get; set; }	
    
                                                    
        public System.Boolean Bid { get; set; }	
    
                                                    
        public System.DateTime Issued { get; set; }	
    
                                                    
        public System.Int64 ExternalID { get; set; }	
    
                                                    
        public System.DateTime IssuedDate { get; set; }	
    
                                                                                                                                                                    }
    
    public class WalletHistoriesDto
    {
                                        
        public System.Int64 ID { get; set; }	
    
                                                    
        public System.Decimal Balance { get; set; }	
    
                                                    
        public System.DateTime Date { get; set; }	
    
                                                                                                        }
    
    public class WalletsDto
    {
                                        
        public System.Int64 ID { get; set; }	
    
                                                    
        public System.String Name { get; set; }	
    
                                                    
        public System.Decimal Balance { get; set; }	
    
                                                    
        public System.Int64 AccountKey { get; set; }	
    
                                                                                                                                                                                        }
    
}
