//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace EveTrader.Core.Model.Central
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CentralModel : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CentralModel object using the connection string found in the 'CentralModel' section of the application configuration file.
        /// </summary>
        public CentralModel() : base("name=CentralModel", "CentralModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CentralModel object.
        /// </summary>
        public CentralModel(string connectionString) : base(connectionString, "CentralModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CentralModel object.
        /// </summary>
        public CentralModel(EntityConnection connection) : base(connection, "CentralModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cache> Cache
        {
            get
            {
                if ((_Cache == null))
                {
                    _Cache = base.CreateObjectSet<Cache>("Cache");
                }
                return _Cache;
            }
        }
        private ObjectSet<Cache> _Cache;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ItemPrices> ItemPrices
        {
            get
            {
                if ((_ItemPrices == null))
                {
                    _ItemPrices = base.CreateObjectSet<ItemPrices>("ItemPrices");
                }
                return _ItemPrices;
            }
        }
        private ObjectSet<ItemPrices> _ItemPrices;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cache EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCache(Cache cache)
        {
            base.AddObject("Cache", cache);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ItemPrices EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItemPrices(ItemPrices itemPrices)
        {
            base.AddObject("ItemPrices", itemPrices);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CentralsModel", Name="Cache")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cache : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cache object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="requestString">Initial value of the RequestString property.</param>
        /// <param name="requestDate">Initial value of the RequestDate property.</param>
        /// <param name="data">Initial value of the Data property.</param>
        public static Cache CreateCache(global::System.Int64 id, global::System.String requestString, global::System.DateTime requestDate, global::System.String data)
        {
            Cache cache = new Cache();
            cache.ID = id;
            cache.RequestString = requestString;
            cache.RequestDate = requestDate;
            cache.Data = data;
            return cache;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RequestString
        {
            get
            {
                return _RequestString;
            }
            set
            {
                OnRequestStringChanging(value);
                ReportPropertyChanging("RequestString");
                _RequestString = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RequestString");
                OnRequestStringChanged();
            }
        }
        private global::System.String _RequestString;
        partial void OnRequestStringChanging(global::System.String value);
        partial void OnRequestStringChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RequestDate
        {
            get
            {
                return _RequestDate;
            }
            set
            {
                OnRequestDateChanging(value);
                ReportPropertyChanging("RequestDate");
                _RequestDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RequestDate");
                OnRequestDateChanged();
            }
        }
        private global::System.DateTime _RequestDate;
        partial void OnRequestDateChanging(global::System.DateTime value);
        partial void OnRequestDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private global::System.String _Data;
        partial void OnDataChanging(global::System.String value);
        partial void OnDataChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CentralsModel", Name="ItemPrices")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ItemPrices : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ItemPrices object.
        /// </summary>
        /// <param name="typeID">Initial value of the TypeID property.</param>
        /// <param name="regionID">Initial value of the RegionID property.</param>
        /// <param name="volumeBuy">Initial value of the VolumeBuy property.</param>
        /// <param name="volumeSell">Initial value of the VolumeSell property.</param>
        /// <param name="averageBuy">Initial value of the AverageBuy property.</param>
        /// <param name="averageSell">Initial value of the AverageSell property.</param>
        /// <param name="maximumBuy">Initial value of the MaximumBuy property.</param>
        /// <param name="maximumSell">Initial value of the MaximumSell property.</param>
        /// <param name="minimumBuy">Initial value of the MinimumBuy property.</param>
        /// <param name="minimumSell">Initial value of the MinimumSell property.</param>
        /// <param name="standardDeviationBuy">Initial value of the StandardDeviationBuy property.</param>
        /// <param name="standardDeviationSell">Initial value of the StandardDeviationSell property.</param>
        /// <param name="medianBuy">Initial value of the MedianBuy property.</param>
        /// <param name="medianSell">Initial value of the MedianSell property.</param>
        public static ItemPrices CreateItemPrices(global::System.Int64 typeID, global::System.Int64 regionID, global::System.Int64 volumeBuy, global::System.Int64 volumeSell, global::System.Decimal averageBuy, global::System.Decimal averageSell, global::System.Decimal maximumBuy, global::System.Decimal maximumSell, global::System.Decimal minimumBuy, global::System.Decimal minimumSell, global::System.Decimal standardDeviationBuy, global::System.Decimal standardDeviationSell, global::System.Decimal medianBuy, global::System.Decimal medianSell)
        {
            ItemPrices itemPrices = new ItemPrices();
            itemPrices.TypeID = typeID;
            itemPrices.RegionID = regionID;
            itemPrices.VolumeBuy = volumeBuy;
            itemPrices.VolumeSell = volumeSell;
            itemPrices.AverageBuy = averageBuy;
            itemPrices.AverageSell = averageSell;
            itemPrices.MaximumBuy = maximumBuy;
            itemPrices.MaximumSell = maximumSell;
            itemPrices.MinimumBuy = minimumBuy;
            itemPrices.MinimumSell = minimumSell;
            itemPrices.StandardDeviationBuy = standardDeviationBuy;
            itemPrices.StandardDeviationSell = standardDeviationSell;
            itemPrices.MedianBuy = medianBuy;
            itemPrices.MedianSell = medianSell;
            return itemPrices;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TypeID
        {
            get
            {
                return _TypeID;
            }
            set
            {
                if (_TypeID != value)
                {
                    OnTypeIDChanging(value);
                    ReportPropertyChanging("TypeID");
                    _TypeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TypeID");
                    OnTypeIDChanged();
                }
            }
        }
        private global::System.Int64 _TypeID;
        partial void OnTypeIDChanging(global::System.Int64 value);
        partial void OnTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 RegionID
        {
            get
            {
                return _RegionID;
            }
            set
            {
                if (_RegionID != value)
                {
                    OnRegionIDChanging(value);
                    ReportPropertyChanging("RegionID");
                    _RegionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RegionID");
                    OnRegionIDChanged();
                }
            }
        }
        private global::System.Int64 _RegionID;
        partial void OnRegionIDChanging(global::System.Int64 value);
        partial void OnRegionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 VolumeBuy
        {
            get
            {
                return _VolumeBuy;
            }
            set
            {
                OnVolumeBuyChanging(value);
                ReportPropertyChanging("VolumeBuy");
                _VolumeBuy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VolumeBuy");
                OnVolumeBuyChanged();
            }
        }
        private global::System.Int64 _VolumeBuy;
        partial void OnVolumeBuyChanging(global::System.Int64 value);
        partial void OnVolumeBuyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 VolumeSell
        {
            get
            {
                return _VolumeSell;
            }
            set
            {
                OnVolumeSellChanging(value);
                ReportPropertyChanging("VolumeSell");
                _VolumeSell = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VolumeSell");
                OnVolumeSellChanged();
            }
        }
        private global::System.Int64 _VolumeSell;
        partial void OnVolumeSellChanging(global::System.Int64 value);
        partial void OnVolumeSellChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal AverageBuy
        {
            get
            {
                return _AverageBuy;
            }
            set
            {
                OnAverageBuyChanging(value);
                ReportPropertyChanging("AverageBuy");
                _AverageBuy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AverageBuy");
                OnAverageBuyChanged();
            }
        }
        private global::System.Decimal _AverageBuy;
        partial void OnAverageBuyChanging(global::System.Decimal value);
        partial void OnAverageBuyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal AverageSell
        {
            get
            {
                return _AverageSell;
            }
            set
            {
                OnAverageSellChanging(value);
                ReportPropertyChanging("AverageSell");
                _AverageSell = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AverageSell");
                OnAverageSellChanged();
            }
        }
        private global::System.Decimal _AverageSell;
        partial void OnAverageSellChanging(global::System.Decimal value);
        partial void OnAverageSellChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MaximumBuy
        {
            get
            {
                return _MaximumBuy;
            }
            set
            {
                OnMaximumBuyChanging(value);
                ReportPropertyChanging("MaximumBuy");
                _MaximumBuy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaximumBuy");
                OnMaximumBuyChanged();
            }
        }
        private global::System.Decimal _MaximumBuy;
        partial void OnMaximumBuyChanging(global::System.Decimal value);
        partial void OnMaximumBuyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MaximumSell
        {
            get
            {
                return _MaximumSell;
            }
            set
            {
                OnMaximumSellChanging(value);
                ReportPropertyChanging("MaximumSell");
                _MaximumSell = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaximumSell");
                OnMaximumSellChanged();
            }
        }
        private global::System.Decimal _MaximumSell;
        partial void OnMaximumSellChanging(global::System.Decimal value);
        partial void OnMaximumSellChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MinimumBuy
        {
            get
            {
                return _MinimumBuy;
            }
            set
            {
                OnMinimumBuyChanging(value);
                ReportPropertyChanging("MinimumBuy");
                _MinimumBuy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinimumBuy");
                OnMinimumBuyChanged();
            }
        }
        private global::System.Decimal _MinimumBuy;
        partial void OnMinimumBuyChanging(global::System.Decimal value);
        partial void OnMinimumBuyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MinimumSell
        {
            get
            {
                return _MinimumSell;
            }
            set
            {
                OnMinimumSellChanging(value);
                ReportPropertyChanging("MinimumSell");
                _MinimumSell = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinimumSell");
                OnMinimumSellChanged();
            }
        }
        private global::System.Decimal _MinimumSell;
        partial void OnMinimumSellChanging(global::System.Decimal value);
        partial void OnMinimumSellChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal StandardDeviationBuy
        {
            get
            {
                return _StandardDeviationBuy;
            }
            set
            {
                OnStandardDeviationBuyChanging(value);
                ReportPropertyChanging("StandardDeviationBuy");
                _StandardDeviationBuy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StandardDeviationBuy");
                OnStandardDeviationBuyChanged();
            }
        }
        private global::System.Decimal _StandardDeviationBuy;
        partial void OnStandardDeviationBuyChanging(global::System.Decimal value);
        partial void OnStandardDeviationBuyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal StandardDeviationSell
        {
            get
            {
                return _StandardDeviationSell;
            }
            set
            {
                OnStandardDeviationSellChanging(value);
                ReportPropertyChanging("StandardDeviationSell");
                _StandardDeviationSell = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StandardDeviationSell");
                OnStandardDeviationSellChanged();
            }
        }
        private global::System.Decimal _StandardDeviationSell;
        partial void OnStandardDeviationSellChanging(global::System.Decimal value);
        partial void OnStandardDeviationSellChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MedianBuy
        {
            get
            {
                return _MedianBuy;
            }
            set
            {
                OnMedianBuyChanging(value);
                ReportPropertyChanging("MedianBuy");
                _MedianBuy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MedianBuy");
                OnMedianBuyChanged();
            }
        }
        private global::System.Decimal _MedianBuy;
        partial void OnMedianBuyChanging(global::System.Decimal value);
        partial void OnMedianBuyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MedianSell
        {
            get
            {
                return _MedianSell;
            }
            set
            {
                OnMedianSellChanging(value);
                ReportPropertyChanging("MedianSell");
                _MedianSell = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MedianSell");
                OnMedianSellChanged();
            }
        }
        private global::System.Decimal _MedianSell;
        partial void OnMedianSellChanging(global::System.Decimal value);
        partial void OnMedianSellChanged();

        #endregion
    
    }

    #endregion
    
}
