//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveTrader.ReleaseNotes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReleaseNotesWindowResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReleaseNotesWindowResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EveTrader.ReleaseNotes.ReleaseNotesWindowResources", typeof(ReleaseNotesWindowResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =============================
        ///
        ///Release notes for 1.2:
        ///* Ignoring transactions
        ///* Backup / restore data
        ///
        ///=============================
        ///
        ///Release notes for 1.1:
        ///*  Added estimated sell/buy time on market orders tab
        ///* Star map route finder
        ///* Some data format changes
        ///* Minor changes 
        ///
        ///=============================
        ///
        ///Release notes for 1.0.26:
        ///* Added date filter for reports
        ///* Reports will show top 15 records
        ///* Some filter optimizations
        ///
        ///=============================
        ///
        ///Release notes for 1.0.24: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReleaseNotesText {
            get {
                return ResourceManager.GetString("ReleaseNotesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eve Trader {0}.
        /// </summary>
        public static string ReleaseNotesTitle {
            get {
                return ResourceManager.GetString("ReleaseNotesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eve Trader updated to {0}.
        /// </summary>
        public static string UpdatedTitle {
            get {
                return ResourceManager.GetString("UpdatedTitle", resourceCulture);
            }
        }
    }
}
