
// <copyright file="DtoGenerator.tt" company="Elvian Empire">
//  Copyright © Elvian Empire. All Rights Reserved.
// </copyright>
// Code generated by a template
using System;
using System.Collections.Generic;

namespace EveTrader.Core.Model.Metric
{
    public class ItemPricesDto
    {
        public Int64 TypeID { get; set; }
        public DateTime LastUpload { get; set; }
        public Decimal MinimumBuy { get; set; }
        public Decimal MinimumSell { get; set; }
        public Decimal MaximumBuy { get; set; }
        public Decimal MaximumSell { get; set; }
        public Decimal MedianBuy { get; set; }
        public Decimal MedianSell { get; set; }
        public Decimal AverageBuy { get; set; }
        public Decimal AverageSell { get; set; }
        public Decimal KurtosisBuy { get; set; }
        public Decimal KurtosisSell { get; set; }
        public Decimal SkewBuy { get; set; }
        public Decimal SkewSell { get; set; }
        public Decimal VarianceBuy { get; set; }
        public Decimal VarianceSell { get; set; }
        public Decimal StandardDeviationBuy { get; set; }
        public Decimal StandardDeviationSell { get; set; }
        public Decimal SimulatedBuy { get; set; }
        public Decimal SimulatedSell { get; set; }
        public Int64 RegionID { get; set; }
    }
}
