
// <copyright file="DtoGenerator.tt" company="Elvian Empire">
//  Copyright © Elvian Empire. All Rights Reserved.
// </copyright>
// Code generated by a template
using System;
using System.Collections.Generic;

namespace EveTrader.Core.Model.Central
{
    public class CacheDto
    {
        public Int64 ID { get; set; }
        public String RequestString { get; set; }
        public DateTime RequestDate { get; set; }
        public String Data { get; set; }
    }
    public class ItemPricesDto
    {
        public Int64 TypeID { get; set; }
        public Int64 VolumeBuy { get; set; }
        public Int64 VolumeSell { get; set; }
        public Decimal AverageBuy { get; set; }
        public Decimal AverageSell { get; set; }
        public Decimal MaximumBuy { get; set; }
        public Decimal MaximumSell { get; set; }
        public Decimal StandardDeviationBuy { get; set; }
        public Decimal StandardDeviationSell { get; set; }
        public Decimal MedianBuy { get; set; }
        public Decimal MedianSell { get; set; }
        public Int64 RegionID { get; set; }
        public Decimal MinimumBuy { get; set; }
        public Decimal MinimumSell { get; set; }
    }
}
